### ISSUE TITLE
You're not authorized to run analysis. Please contact the project administrator

### ISSUE THREAD

**Issue by gigi** [tkgregory/integration-tests-with-jacoco-issue#4]
Latest 9.9 sonarqube image gives error. 

```
> Task :sonarqube FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> You're not authorized to run analysis. Please contact the project administrator.

```

The only possible solution I found to force it work out of the box is to use deprecated properties:
sonar.login=admin
sonar.password=admin

**Comment by tkgregory** [comment]
Thanks for reporting. I've gone with your suggestion. 

I think we need a way to generate the authentication token automatically to avoid using `sonar.password` and therefore the deprecation warning.
